repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-json
      name: Check JSON files
      exclude: (^|/)\.(vscode|devcontainers)/
    - id: check-yaml
      name: Check YAML files
    - id: check-toml
      name: Check TOML files
    - id: end-of-file-fixer
      name: Ensure proper file endings
    - id: trailing-whitespace
      name: Remove unnecessary whitespace from code
      args: [--markdown-linebreak-ext=md]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
    - id: ruff
      name: Lint Python code with ruff
      types_or: [python, pyi, jupyter]
      args: [--fix, "--config", "pyproject.toml"]
    - id: ruff-format
      name: Format Python code with ruff
      types_or: [python, pyi, jupyter]
      args: ["--config", "pyproject.toml"]
