# https://taskfile.dev

version: "3"

tasks:
  setup:
    cmds:
      - uv sync --all-groups --all-extras
      - uv run pre-commit install
    desc: "Setup development environment"

  lint:
    cmds:
      - uv run pre-commit run --all-files
    desc: "Run linters"

  test:
    cmds:
      - uv run pytest
    desc: "Run tests"

  bump-version:
    cmds:
      - uv version --bump {{.BUMP}}
      - git tag v$(uv version --short)
    requires:
      vars:
        - name: BUMP
          enum: [patch, minor, major]
    desc: "Bump project version"
