name: "Release to PyPI"

on:
    push:
        tags:
            - v*
            - "!v*a*"
            - "!v*b*"
            - "!v*rc*"
            - "!v*.post*"
            - "!v*.dev*"

jobs:
    run:
        runs-on: ubuntu-latest
        environment:
            name: pypi
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Check out source code
              uses: actions/checkout@v5

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version-file: ".python-version"

            - name: Build package
              run: uv build

            - name: Publish to PyPI
              run: uv publish
